### ISSUE TITLE
Cannot get 'pagelist'

### ISSUE THREAD

**Issue by cedrusx** [gaocegege/csdn-blog-export#1]
Hi Gao, is this tool still supposed to work for now? I got an error as below. Could you have a check? Thanks!

Traceback (most recent call last):
  File "main.py", line 202, in <module>
    main(sys.argv[1:])
  File "main.py", line 199, in main
    parser.run(url, page, form)
  File "main.py", line 155, in run
    self.getAllArticleLink(url)
  File "main.py", line 135, in getAllArticleLink
    self.getPageNum(self.get(url))
  File "main.py", line 122, in getPageNum
    res = self.getContent(soup).find(id='papelist').span
AttributeError: 'NoneType' object has no attribute 'span'

**Comment by gaocegege** [comment]
嗯，这个是一年前写的了，晚上我去看看

**Comment by gaocegege** [comment]
可以提供下你的username么

**Comment by cedrusx** [comment]
snowflurry

2016年4月30日星期六，Ce Gao notifications@github.com 写道：

**Comment by gaocegege** [comment]
是因为你的博文不到一页，所以这样报错~我去fix一下

**Comment by cedrusx** [comment]
哈哈 非常感谢！

**Comment by gaocegege** [comment]
ok，fix了~

**Comment by cedrusx** [comment]
赞美！
