### ISSUE TITLE
为什么我按照你的方法导出 报错

### ISSUE THREAD

**Issue by foqianyilishazi** [gaocegege/csdn-blog-export#2]
Phase 1: Getting the link
Traceback (most recent call last):
  File "./main.py", line 209, in <module>
    main(sys.argv[1:])
  File "./main.py", line 206, in main
    parser.run(url, page, form)
  File "./main.py", line 162, in run
    self.getAllArticleLink(url)
  File "./main.py", line 142, in getAllArticleLink
    self.getPageNum(self.get(url))
  File "./main.py", line 123, in getPageNum
    pageList = self.getContent(soup).find(id='papelist')
  File "./main.py", line 56, in getContent
    return soup.find(id='container').find(id='body').find(id='main').find(class_='main')
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by gaocegege** [comment]
你好，可能是太久没维护了，你的博客地址是什么

**Comment by foqianyilishazi** [comment]
http://blog.csdn.net/qq_18670721

**Comment by gaocegege** [comment]
@bujieshi 

我这边可以啊

```bash
./main.py -u qq_18670721
```

```
Work in Page 1
Work in Page 2
Phase 2: Exporting
Count of Articles: 27
Work in http://blog.csdn.net//qq_18670721/article/details/73177662
Work in http://blog.csdn.net//qq_18670721/article/details/72954473
Work in http://blog.csdn.net//qq_18670721/article/details/72954378
Work in http://blog.csdn.net//qq_18670721/article/details/72923221
Work in http://blog.csdn.net//qq_18670721/article/details/72923061
Work in http://blog.csdn.net//qq_18670721/article/details/72922629
Work in http://blog.csdn.net//qq_18670721/article/details/72922278
Work in http://blog.csdn.net//qq_18670721/article/details/72922237
Work in http://blog.csdn.net//qq_18670721/article/details/72922219
Work in http://blog.csdn.net//qq_18670721/article/details/72922201
Work in http://blog.csdn.net//qq_18670721/article/details/72922131
Work in http://blog.csdn.net//qq_18670721/article/details/51861268
Work in http://blog.csdn.net//qq_18670721/article/details/51323473
Work in http://blog.csdn.net//qq_18670721/article/details/51162336
Work in http://blog.csdn.net//qq_18670721/article/details/51161228
Work in http://blog.csdn.net//qq_18670721/article/details/50524214
Work in http://blog.csdn.net//qq_18670721/article/details/50433760
Work in http://blog.csdn.net//qq_18670721/article/details/50432892
Work in http://blog.csdn.net//qq_18670721/article/details/50384766
Work in http://blog.csdn.net//qq_18670721/article/details/50326673
Work in http://blog.csdn.net//qq_18670721/article/details/50296581
Work in http://blog.csdn.net//qq_18670721/article/details/50261823
Work in http://blog.csdn.net//qq_18670721/article/details/50171623
Work in http://blog.csdn.net//qq_18670721/article/details/50171621
Work in http://blog.csdn.net//qq_18670721/article/details/50171619
Work in http://blog.csdn.net//qq_18670721/article/details/50171615
Work in http://blog.csdn.net//qq_18670721/article/details/49667203
Over. If has any problem, contact me with https://github.com/gaocegege/csdn-blog-export/issues
```

**Comment by foqianyilishazi** [comment]
我这边down 不下来 ，你那边可以down 下来的话 你可以帮我down 下来  然后右键发给我吗？ 谢谢了！

**Comment by gaocegege** [comment]
Markdown 么，告诉我你的邮箱

**Comment by foqianyilishazi** [comment]
恩恩  markDown  foqianyilishazi@gmail.com

**Comment by gaocegege** [comment]
发了，有什么问题在这里说吧

**Comment by janrone** [comment]
我也报错呢 

Work in Page 1
Work in Page 2
Work in Page 3
Work in Page 4
Work in Page 5
Work in Page 6
Work in Page 7
Work in Page 8
Work in Page 9
Work in Page 10
Work in Page 11
Work in Page 12
Work in Page 13
Work in Page 14
Work in Page 15
Work in Page 16
Phase 2: Exporting
Count of Articles: 240

Traceback (most recent call last):
  File "./main.py", line 210, in <module>
    main(sys.argv[1:])
  File "./main.py", line 207, in main
    parser.run(url, page, form)
  File "./main.py", line 171, in run
    self.export(form)
  File "./main.py", line 155, in export
    exporter.run(link, link.split('/')[7], form)
  File "./main.py", line 100, in run
    self.export(link, f, form)
  File "./main.py", line 87, in export
    detail = self.getContent(soup).find(id='article_details')
  File "./main.py", line 57, in getContent
    return soup.find(id='container').find(id='body').find(id='main').find(class_='main')
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by foqianyilishazi** [comment]
我的是博主帮我导出的！
